### ISSUE TITLE
Add addin to website to allow for automatic documentation

### ISSUE THREAD

**Issue by gep13** [NinetailLabs/Cake.VersionReader#1]
i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#152

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by gep13** [comment]
@DeadlyEmbrace just wanted to touch base to see if you had thought about doing this. Thanks!

**Comment by DeadlyEmbrace** [comment]
@gep13 Sorry, been meaning to do this but things have just been a little hectic. Will try and get around to it this week. Really excited to get the plugin documented :)

**Comment by gep13** [comment]
Nice one! Let me know if you have any questions.
