### ISSUE TITLE
Add netstandard1.6 support to VersionReader

### ISSUE THREAD

**Issue by KianaKaslana** [NinetailLabs/Cake.VersionReader#10]
AssemblyName.GetAssembly is not available in netcore but has the equivalent in [System.Runtime.Loader](https://www.nuget.org/packages/System.Runtime.Loader/) which can be used as follows:

`
AssemblyLoadContext.Default.LoadFromAssemblyPath(path).GetName().Version;
`

Note that System.Runtime.Loader does not support .net4.6/.net4.5 so will need to add separate logic for those as well as implementing a test class to test the netcore parts

**Comment by DeadlyEmbrace** [comment]
Obsolete as .netstandard2.0 seem to have everything we need
