### ISSUE TITLE
Reading FileVersion instead of AssemblyVersion

### ISSUE THREAD

**Issue by dittodhole** [NinetailLabs/Cake.VersionReader#13]
Please see https://stackoverflow.com/questions/11350008/how-to-get-exe-file-version-number-from-file-path

So, instead of loading up the assembly and accessing the attributes, one should rather read the version with `System.Diagnostics.FileVersionInfo.FileVersion` (which will also match the properties-dialog of windows explorer).

Best
Andreas

**Comment by DeadlyEmbrace** [comment]
Will take a look when I have some free time, thanks for raising this
