### ISSUE TITLE
Would it be possible to use the Cake Contrib Icon for your NuGet Package?

### ISSUE THREAD

**Issue by gep13** [NinetailLabs/Cake.VersionReader#5]
Thanks again for creating this Cake Addin, we really appreciate the effort that you have put in to creating it.  

We, the Cake Team, recently announced a new Cake Contrib Icon, details of which can be found here:

http://cakebuild.net/blog/2017/06/new-cake-contrib-icon

Would you consider changing the nuspec file for your NuGet Package to use this new Cake Contrib Icon?  If so, the recommended URL to use is:

https://cdn.rawgit.com/cake-contrib/graphics/a5cf0f881c390650144b2243ae551d5b9f836196/png/cake-contrib-medium.png

Details of the above URL can be found in the repository here:

https://github.com/cake-contrib/graphics

Please let me know if you have any questions.

**Comment by DeadlyEmbrace** [comment]
Hi, just a little busy at the moment with other project, but will try to bring all of my cake packages icons up to date in the next week or so. 👍

**Comment by gep13** [comment]
@DeadlyEmbrace not a problem.  I just wanted to bring this to your attention.  Thanks

**Comment by DeadlyEmbrace** [comment]
@gep13  My apologies for taking so long to finish this, had a personal project that needed a lot of attention.

**Comment by gep13** [comment]
@DeadlyEmbrace not a problem at all!  Thank you very much for taking care of this.
